<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace GPBMetadata\Proto;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a88020a1070726f746f2f757365722e70726f746f12046772706322260a" .
            "09486952657175657374120c0a046e616d65180120012809120b0a037365" .
            "78180220012805222f0a1255736572526573706f6e7365456e7469747912" .
            "0c0a046e616d65180120012809120b0a0373657818022001280522530a0a" .
            "4869526573706f6e7365120c0a04636f6465180120012805120f0a076d65" .
            "737361676518022001280912260a046461746118032001280b32182e6772" .
            "70632e55736572526573706f6e7365456e7469747932380a0568656c6c6f" .
            "122f0a0873617948656c6c6f120f2e677270632e4869526571756573741a" .
            "102e677270632e4869526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

